version: "3"
services:
       carousel-app:
           container_name: carouselnode
           image: carouselNode
           restart: on-failure
           build: .
           ports:
             - "3003:3003"
           links:
             - mongo
       mongo:
             container_name: carousel-mongo
             image: mongo
             volumes:
               - ./data:/data/db
             ports:
               - '27017:27017'